server:
  port: 4000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${data}?serverTimezone=Asia/Seoul
    username: ${user}
    password: ${pw}

  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB